### ISSUE TITLE
Unused classical registers omitted from generated PHIR

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-phir#237]
**Describe the bug**

If a pytket circuit containing unused classical registers is converted to PHIR, these registers are missing from the generated PHIR.

**To Reproduce**

```python
from pytket.circuit import Circuit
from pytket.phir.api import pytket_to_phir


def test():
    circ = Circuit()
    a = circ.add_c_register("a", 1)
    phir = pytket_to_phir(circ)
    print(phir)


test()
```

Result:
```
{"format": "PHIR/JSON", "version": "0.1.0", "metadata": {"source": "pytket-phir v0.8.1"}, "ops": []}
```

**Expected behavior**

The generated PHIR should include the classical register. (After emulation in pecos we expect its value to be 0.)

**Additional context**

This issue arose from trying to emulate a circuit that had been compiled down to a conditional `Phase` operation (conditioned on an otherwise-unused register). Since `Phase` operations are ignored by PHIR the bit was thrown away by the converter. But even completely unused bits should be preserved.

**Comment by qartik** [comment]
I looked into this. The issue is that during sharding we use `Circuit.get_commands()` iterator, which doesn't include the classical `BitRegister`s unless they are used. From sharding on, we abandon `Circuit` completely and hence completely miss out on unused classical bits.

I think if we take the `Circuit` down to `phirgen` we should be able to retain this information. One other improvement will be to omitting the code inferring cbits/qbits and their dimensions from the list of shards and instead using the info from `Circuit` directly`.

@cqc-alec and @neal-erickson what do you think?

**Comment by cqc-alec** [comment]
> I looked into this. The issue is that during sharding we use `Circuit.get_commands()` iterator, which doesn't include the classical `BitRegister`s unless they are used. From sharding on, we abandon `Circuit` completely and hence completely miss out on unused classical bits.
> 
> I think if we pass the `Circuit` down to `phirgen` (along with placed shards) we should be able to retain this information. One other improvement will be to omitting the code inferring cbits/qbits and their dimensions from the list of shards and instead using the info from `Circuit` directly.
> 
> @cqc-alec and @neal-erickson what do you think?

Sound reasonable, or at lease pass `Circuit.bits` (I don't think we care about unused qubits.)
